// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyyvmabeweaswyiexphe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95eXZtYWJld2Vhc3d5aWV4cGhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTE3NDksImV4cCI6MjA2OTk4Nzc0OX0.QFXPG0Z6NO9gRSho7pvH-WzqFpofy7Y2tCDkhRG424k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});